### ISSUE TITLE
Epic: add missing functionality back to EUDEMO

### ISSUE THREAD

**Issue by je-cook** [Fusion-Power-Plant-Framework/bluemira#1896]
## Description of issue / requirement to address

There is some functionality of EUDEMO that previously existed and needs to be replaced

- [x]  Remaining major components eg Cryostat, Radiation shield (#1858)
- Ports 
    -  Upper port 
        - [x]  conversion of upper port code in `maintanence.py` (#1858)
        - [x]  Builder #2092 
    - Equatorial port
        - [x] Designer #1900
        - [x] Builder #1900 
    - Lower port
       - [x] Designer #1901
       - [x] Builder
    - [x] Connections between ports eg vv thermal shield to cryostat thermal shield
        - [x] #2160 for upper and eq ports 
        - [x] #2380 
        - [x] #2388  
    - [x] Plugs for ports #2410 
- [x] #958
- [x] #957 
- [x] #1899
- [x] Viewing of Sectors of reactor for saving and visual inspection (#2035)
    - [x] Organisation of reactor tree (#1076)
