### ISSUE TITLE
EPIC: Optimisation feature branch

### ISSUE THREAD

**Issue by hsaunders1904** [Fusion-Power-Plant-Framework/bluemira#2189]
## Description of issue / requirement to address

List of tasks to address before `feature/new_optimisation_module` can be merged into develop.

- [x] Port existing optimisation routines
  - Normal optimisations:
    - [x] #2231
    - [x] #2383
    - [x] #2225
    - [x] #2221 
  - Geometry optimisations:
    - [x] #2237
    - [x] #2267
    - [x] #2233
- [x] #2190
- [x] #2203
- [x] #2227
- [x] #2256
- [x] #2274
- [x] #2335
- [x] #2252
- [x] #2337
- [x] #2340
- [x] Handle `ad_args` for automatic differentiation [sic] of objective and constraints
   - @hsaunders1904: I would argue if you wanted to customise this automatic differentiation, you should implement `df_objective`/`df_constraint` and use `approx_derivative`.
- [x] ~Tests for equality constraints~ (managed to throw some of these together when testing the optimisation problem class)
- [x] #2414
  - This could be a good opportunity to have a think about the visibility of the optimisation module's submodules, which are a bit of a mess of underscores at the moment.
- [x] Remove geometry constraint registry (also #2420) 
  - The constraints should live on the geometry parametrisations
- [x] #2416
  - This default could be based on which algorithm is used, which is how SciPy handles it.
- [x] #2415
- [x] #2417

## Non-blocking 
Issues that can be resolved after the feature branch has been merged into develop

- [x] #2332
- [x] Do not warn that maximum iterations reached when using ISRES (max iterations are usually expected to be reached) #2499 
  - Maybe just a debug or info message would suffice here
- [x] #3024
- [x] Add further defaults to the `AlgorithmDefaultTolerances` covered in #2447
