### ISSUE TITLE
Enable DOC201

### ISSUE THREAD

**Issue by je-cook** [Fusion-Power-Plant-Framework/bluemira#3504]
## Description of issue / requirement to address

As of ruff 0.5.6 (#3501) it is possible to check we have return documentation in our api docs as a lint. We should enable this.
There is a list of modules that can be removed individually on completion from pyproject.toml.

Just create an issue with those you are fixing, with a proper issue name
## Proposed solution

- [x] "eudemo/eudemo/*" = ["DOC201"]  #3536
- [x] "examples/*" = ["DOC201"]  # 51
- [x] "bluemira/utilities/*" = ["DOC201"]  # 39
- ~~"bluemira/structural/*" = ["DOC201"]~~  # 22  will be tackled on refactor
- [x] "bluemira/radiationtransport" #3601 
- [x] "bluemira/plasma_physics/*" = ["DOC201"]  #3550 
- [x] "bluemira/optimisation/*" = ["DOC201"]  #3556 
- [x] "bluemira/mesh/*" = ["DOC201"]  # 10
- [x] "bluemira/materials/*" = ["DOC201"]  # 62
- [x] "bluemira/magnetostatics/*" = ["DOC201"]  #3550 #3602
- [x] "bluemira/geometry/*" = ["DOC201"]  #3559 
- [x] "bluemira/fuel_cycle/*" = ["DOC201"]  # 19
- [x] "bluemira/equilibria/*" = ["DOC201"]  # 214
- [x] "bluemira/display/*" = ["DOC201"] #3556 
- [x] "bluemira/codes/*" = ["DOC201"]  # 239
- [x] "bluemira/builders/*" = ["DOC201"]  # 69
- [x] "bluemira/base/*" = ["DOC201"]  #3565 
- [x] "bluemira/balance_of_plant/*" = ["DOC201"]  # 5

**Comment by je-cook** [comment]
See #3536 for style, the colon is important so that the return type and description are correctly rendered in the docs eg
```python
"""
Returns
-------
:
    Description
"""

See https://numpydoc.readthedocs.io/en/latest/format.html#returns for multiple arguments
